[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = 'pip3 install --user --upgrade neovim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1

  set completeopt+=noinsert

  autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
  autocmd InsertLeave * if pumvisible() == 0|pclose|endif

  inoremap <expr><CR> pumvisible() ? deoplete#close_popup() : "\<CR>"

  imap <expr><TAB> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  call deoplete#custom#option('omni_patterns', {
  \ 'complete_method': 'omnifunc',
  \ 'terraform': '[^ *\t"{=$]\w*',
  \})

  call deoplete#initialize()
'''
on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugin]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
build = 'gem install neovim'
on_ft = 'terraform'
depends_on = ['deoplete.nvim', 'vim-terraform']
